project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('primary_setup.urls')),
    path('', include('otrans.urls')),
    path('report/', include('report.urls')),
    path('sheet/', include('sheet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sms/', include('sms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('customer-balance/', views.customer_balance, name='customer_balance'),
    path('customer-statement/', views.customer_statement, name='account_statement'),
    
    path('admission-report/', views.admission_report, name='customer_report'),
    path('dps_report/', views.dps_report, name='dps_report'),
    path('share_report/', views.share_report, name='share_report'),
    
    path('general_ledger/', views.general_ledger, name='general_ledger'),
    path('bank-transactions/', views.bank_transactions, name='bank_transactions'),
    
    path('monthly_top_sheet_report/', views.monthly_top_sheet_report, name='monthly_top_sheet_report'),
    path('yearly_top_sheet_report/', views.yearly_top_sheet_report, name='yearly_top_sheet_report'),


    path('voucher_report/', views.voucher_report, name='voucher_report'),
    
    
    # path('balance_sheet/', views.balance_sheet, name='balance_sheet'),
    # path('user_log/', views.user_log, name='user_log'),
    # path('user_entry_summary/', views.user_entry_summary, name='user_entry_summary'),
    # path('user_wise_entry_summary/', views.user_wise_entry_summary, name='user_wise_entry_summary'),
    # path('ReceivePayment/', views.ReceivePayment, name='ReceivePayment'),
    # path('ProfitLoss/', views.ProfitLoss, name='ProfitLoss'),
]

sms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sms_single/', views.sms_single, name='sms_single'),
    path('sms_bulk/', views.sms_bulk, name='sms_bulk'),
    path('sms_customer/', views.sms_customer, name='sms_customer'),
    path('sms_report/', views.sms_report, name='sms_report'),
]

report/models.py
from django.db import models
from django.utils import timezone
from primary_setup.models import CustomUser
from app1.models import Customer
import socket
from django.db.models import Sum

def get_ip_address():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip_address = s.getsockname()[0]
        s.close()
        return ip_address
    except Exception as e:
        return str(e)



from django.utils import timezone

class UserLog(models.Model):
    TRANSACTION_TYPE_CHOICES = [
        ('cash_in', 'Cash In'),
        ('cash_out', 'Cash Out'),
    ]
    CASHFLOW1_TYPE_CHOICES = [
        ('income', 'Income'),
        ('expense', 'Expense'),
    ]
    CASHFLOW2_TYPE_CHOICES = [
        ('receive', 'Receive'),
        ('payment', 'Payment'),
    ]

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    
    processed_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    action = models.CharField(max_length=300, null=True, blank=True)
    logs_action = models.CharField(max_length=300, null=True, blank=True)

    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES, null=True, blank=True)
    cashflow_type1 = models.CharField(max_length=10, choices=CASHFLOW1_TYPE_CHOICES, null=True, blank=True)
    cashflow_type2 = models.CharField(max_length=10, choices=CASHFLOW2_TYPE_CHOICES, null=True, blank=True)

    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    timestamp = models.DateField(null=True, blank=True)  # Allowing manual input but can be auto-set
    ip_address = models.CharField(max_length=300, null=True, blank=True)
    description = models.CharField(max_length=300, null=True, blank=True)
    VoucherID = models.CharField(max_length=50, null=True, blank=True)
    
    trx = models.BooleanField(null=True, blank=True)

    def save(self, *args, **kwargs):
        # Auto set timestamp only if it's not provided
        if self.timestamp is None:
            self.timestamp = timezone.now()

        if not self.ip_address:
            self.ip_address = get_ip_address()

        if not self.logs_action:
            if not self.transaction_type and not self.cashflow_type1 and not self.cashflow_type2:
                self.transaction_type = 'cash_in'
                self.cashflow_type1 = 'income'
                self.cashflow_type2 = 'receive'
            if self.trx:
                self.transaction_type = 'cash_out'
                self.cashflow_type1 = 'expense'
                self.cashflow_type2 = 'payment'

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.processed_by.username if self.processed_by else 'Unknown'} - {self.transaction_type} at {self.timestamp}"
    
    @staticmethod
    def get_sum_of_amounts_by_action():
        """
        Returns a dictionary with the sum of amounts for each unique action.
        """
        return UserLog.objects.values('action').annotate(total_amount=Sum('amount')).order_by('action')

report/forms.py
from django import forms
from primary_setup.models import CustomUser, DPSScheme, VoucherCategory
from report.models import UserLog





class CustomerSearchForm(forms.Form):
    start_date = forms.DateField(label='Start Date', widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'type': 'date'}))



class DPSReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    scheme_name = forms.ModelChoiceField(
        queryset=DPSScheme.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    status = forms.ChoiceField(
        choices=[('all', 'All'), ('active', 'Active'), ('closed', 'Closed')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        # user = kwargs.pop('user', None)
        super(DPSReportForm, self).__init__(*args, **kwargs)
        
        # if user:
        self.fields['scheme_name'].queryset = DPSScheme.objects.filter()


class ShareReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )



class VoucherReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=True
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=True
    )
    voucher_category = forms.ModelChoiceField(
        queryset=VoucherCategory.objects.filter(),  # add filter if you need like .filter(status='active')
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False,
        empty_label="All"
    )

    def __init__(self, *args, **kwargs):
        super(VoucherReportForm, self).__init__(*args, **kwargs)
        self.fields['voucher_category'].queryset = VoucherCategory.objects.all()






class UESReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    staff = forms.ModelChoiceField(
        queryset=CustomUser.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(UESReportForm, self).__init__(*args, **kwargs)
        
        if user:
            self.fields['staff'].queryset = CustomUser.objects.filter()
    

class UWESReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(UWESReportForm, self).__init__(*args, **kwargs)
        
        
    

class GeneralLedgerForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        required=False
    )
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=False
    )




class ReceivePaymentReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ReceivePaymentReportForm, self).__init__(*args, **kwargs)
        

class ProfitLossReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(ProfitLossReportForm, self).__init__(*args, **kwargs)


from django import forms
import calendar
from datetime import datetime

MONTH_CHOICES = [(str(i), calendar.month_name[i]) for i in range(1, 13)]
YEAR_CHOICES = [(str(year), str(year)) for year in range(2020, datetime.now().year + 1)]

class ReportForm(forms.Form):
    month = forms.ChoiceField(
        choices=MONTH_CHOICES,
        label='Month',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    year = forms.ChoiceField(
        choices=YEAR_CHOICES,
        label='Year',
        widget=forms.Select(attrs={'class': 'form-control'})
    )


class YearlyTopSheetForm(forms.Form):
    year = forms.ChoiceField(
        choices=YEAR_CHOICES,
        label='Year',
        widget=forms.Select(attrs={'class': 'form-control'})
    )







class AccountStatementForm(forms.Form):
    account_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account No.'}),
        required=True
    )
    start_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date From'}),
        required=False
    )
    end_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Date To'}),
        required=False
    )

templates/report/account_statment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Account Statment{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>Account Statment</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'account_statement' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}

templates/report/bank_transaction_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank Statement</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        form{
            display: flex;
            flex-direction: column;
            width: 200px;
            gap: 5px;
        }
        @media print {
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>

    <div style="text-align: center">
        <h2>আশারা প্রকল্প</h2>
        <h4>সুদমুক্ত বাণিজ্যিক প্রকল্প</h4>
        <span style="background: black;color: white;padding: 5px 15px;border-radius: 50px;">স্থায়ী কার্যালয়</span>
        <p>নদীপার, খিলগাঁও, ঢাকা-১২১৯</p>
    </div>


<!-- Bank Balances Table -->
<br><br>
<span><b>Bank Balances Table</b></span>
<table>
    <thead>
        <tr>
            <th>Bank</th>
            <th>Current Balance</th>
        </tr>
    </thead>
    <tbody>
        {% for b in banks %}
            <tr>
                <td>{{ b.bank_name }}</td>
                <td>{{ b.balance }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td>Total</td>
            <td>{{total_balance}}</td>
        </tr>
    </tbody>
</table>


<!-- Transactions Table -->
{% if transactions %}
<br><br><br>
<span><b>Transactions Table</b></span>
<div>
    {% if bank %}
        <span>Bank: {{ bank.bank_name }}</span>
    {% else %}
        <span>Bank: All Banks</span>
    {% endif %}
    <br>
    {% if start_date %}
    <span>Date: {{ start_date }} - {{ end_date }}</span>
    {% endif %}
</div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Bank Name</th>
                <th>Deposit</th>
                <th>Withdraw</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.date|date:"Y-m-d" }}</td>
                    <td>{{ transaction.bank.bank_name }}</td>
                    {% if transaction.transaction_type == 'deposit' %}
                        <td>{{ transaction.amount }}</td>
                        <td></td>
                    {% else %}
                        <td></td>
                        <td>{{ transaction.amount }}</td>
                    {% endif %}
                    <td>{{ transaction.note|default:"" }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2" style="text-align: right">Total</td>
                <td>{{ total_deposit|floatformat:"2" }}</td>
                <td>{{ total_withdraw|floatformat:"2" }}</td>
                <td></td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: right">Net Balance</td>
                <td colspan="3">{{ net_balance|floatformat:"2" }}</td>
            </tr>
        </tbody>
    </table>

{% elif error %}
    <p>{{ error }}</p>
{% endif %}


<div style="text-align: center; margin-top: 20px;" class="no-print">
  <button onclick="window.history.back();">Go Back</button>
  <button onclick="window.print();">Print</button>
  <button onclick="window.location.href='{% url 'home' %}';">home</button>
</div>

<!-- Transactions Table -->
<form method="post" class="no-print">
    {% csrf_token %}
    <span><b>Generate Transactions Table</b></span>
  <label for="start_date">Start Date:</label>
  <input type="date" id="start_date" name="start_date" required>

  <label for="end_date">End Date:</label>
  <input type="date" id="end_date" name="end_date" required>

  <label for="bank">Bank:</label>
  <select id="bank" name="bank" required>
      <option value="all">All Banks</option>
      {% for bank in banks %}
          <option value="{{ bank.id }}">{{ bank.bank_name }}</option>
      {% endfor %}
  </select>

  <button type="submit">View Transactions</button>
</form>


</body>
</html>

templates/report/customer_balance.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Customer Balance{% endblock %}

{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'report/customer_balance.css' %}">
{% endblock %}

{% block content %}

<h2 class="section-title">Customer Balance</h2>

<div class="div1">
    <table>
        <tr>
            <th>Account No.</th>
            <td>{{ customer.account_number }}</td>
        </tr>
        <tr>
            <th>Customer Name</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>Father</th>
            <td>{{ customer.customer_father }}</td>
        </tr>
        <tr>
            <th>Mother</th>
            <td>{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>Mobile Number</th>
            <td>{{ customer.customer_mobile }}</td>
        </tr>
        <tr>
            <th>Current Address</th>
            <td>{{ customer.customer_current_address }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ customer.customer_permanent_address }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.customer_photo %}
        <div>
            <img src="{{ customer.customer_photo.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>


<div class="balance-summary">
    <div class="balance-box">
        <h3>General AC Balance</h3>
        <p>TK <strong>{{ general_savings|floatformat:2 }}</strong></p>
    </div>
    <div class="balance-box">
        <h3>Savings AC Balance</h3>
        <p>TK <strong>{{ special_savings|default:"0.00"|floatformat:2 }}</strong></p>
    </div>
    <div class="balance-box">
        <h3>DPS AC Balance</h3>
        <p>TK <strong>{{ dps_balance|floatformat:2 }}</strong></p>
    </div>
    <div class="balance-box">
        <h3>Share AC Balance</h3>
        <p>TK <strong>{{ share_balance|floatformat:2 }}</strong></p>
    </div>
</div>



{% endblock %}

templates/report/share.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Share Account Report{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>Share Account Report</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'share_report' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/report/ues.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Entry Summary{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>User Entry Summary</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'user_entry_summary' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}

templates/report/ues_print.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'report/styles.css' %}">
    <title>User Entry Summary</title>
</head>
<body>

    <div style="text-align: center;">
        <h1>{{somity_name}}</h1>
        <h3>INTEGRITY IS OUR HALLMARK</h3>
        <hr>
        <h3>User Entry Summary</h3>
        <h3>Branch Name: {{ branch }}</h3>
        <h3>User Name: {{ staff }}</h3>
        <h3>Date: {{ start_date }} to {{end_date}}</h3>
    </div>

    <div class="container">   
        <table class="table">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Timestamp</th>
                    <th>Branch</th>
                    <th>Somity</th>
                    <th>Account</th>
                    <th>Customer</th>
                    <th>Action</th>
                    <th>Transaction Type</th>
                    <th>Cash In</th>
                    <th>Cash Out</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ log.timestamp }}</td>
                    <td>{{ log.branch }}</td>
                    <td>{{ log.customer.group }}</td>
                    <td>{{ log.customer.account_no }}</td>
                    <td>{{ log.customer.customer_name }}</td>
                    <td>{{ log.action }}</td>
                    <td>{{ log.get_transaction_type_display }}</td>
                    <td>
                        {% if log.transaction_type == 'cash_in' %}
                            {{ log.amount }}
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>
                    <td>
                        {% if log.transaction_type == 'cash_out' %}
                            {{ log.amount }}
                        {% else %}
                            &nbsp;
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="8" class="text-right"><strong>Total:</strong></td>
                    <td><strong>{{ total_cash_in | floatformat:2  }}</strong></td>
                    <td><strong>{{ total_cash_out | floatformat:2 }}</strong></td>
                </tr>
            </tbody>
        </table>
    </div>
    
    

    <div style="margin-top: 20px; display: flex; justify-content: space-between;">
        <p>Prepared by: _____________________</p>
        <p>Approved by: _____________________</p>
    </div>

    <div style="text-align: center; margin-top: 20px;" class="no-print">
        <button onclick="window.history.back();">Go Back</button>
        <button onclick="window.print();">Print</button>
        <button onclick="window.location.href='{% url 'home' %}';">Home</button>
    </div>
</body>
</html>

templates/report/user_log.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Log{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<style>
    th {
        background: #0951a2;
        color: white;
    }
</style>
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.css">
{% endblock %}

{% block content %}
<div>
    <div>
        <h2>
            User Log
        </h2>        
    </div>

    <div class="table-container">
        <table id="myTable" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Timestamp</th>
                    <th>Type</th>
                    <th>Description</th>
                    <th>Branch</th>
                    <th>Users</th>
                    <th>IP Address</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs_actions %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ log.timestamp }}</td>
                    <td>{{ log.logs_action }}</td>
                    <td>{{ log.description }}</td>
                    <td>{{ log.branch }}</td>
                    <td>{{ log.processed_by.username}}</td>
                    <td>{{ log.ip_address}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
        });
    </script>
{% endblock %}

templates/report/uwes.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Wise Entry Summary{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'report/styles.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
{% endblock %}
{% block content %}

<div>
   <h2>User Wise Entry Summary</h2>
</div>

<div class="box">
    <form method="POST" action="{% url 'user_wise_entry_summary' %}">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input type="submit" value="Report" name="search">
        </div>
    </form>
</div>


{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_start_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");

        $("#id_end_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: null,
            placeholder: "yyyy-mm-dd",
        }).attr("placeholder", "yyyy-mm-dd");
    });
</script>
{% endblock %}