app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('home/', views.home, name='home'),
    path('customer_home/', views.customer_home, name='customer_home'),
    path('set_language/', views.set_language, name='set_language'),
    path('customer-login/', views.customer_login, name='customer_login'),
    path('customer-logout/', views.customer_signout, name='customer_logout'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('access-denied/', views.access_denied, name='access_denied'),

    path('manage-permissions/', views.manage_permissions, name='manage_permissions'),

    path('customers-add/', views.customer_add, name='customer_add'),
    path('customers-list/', views.customer_list, name='customer_list'),
    path('customers-details/<int:id>/', views.customer_details, name='customer_details'),
    path('customers-edit/<int:id>/', views.customer_edit, name='customer_edit'),

    path('general-list/', views.general_list, name='general_list'),
    path('general-deposit/<int:id>/', views.general_deposit, name='general_deposit'),
    path('general-withdraw/<int:id>/', views.general_withdraw, name='general_withdraw'),
    path('general-transactions/<int:id>/', views.general_transaction_history, name='general_transaction_history'),
    # path('general-deposit-search/', views.general_deposit_search, name='general_deposit_search'),
    # path('general-withdraw-search/', views.general_withdraw_search, name='general_withdraw_search'),

    path('savings-list/', views.savings_list, name='savings_list'),
    path('savings-deposit/<int:id>/', views.savings_deposit, name='savings_deposit'),
    path('savings-withdraw/<int:id>/', views.savings_withdraw, name='savings_withdraw'),
    path('savings-transactions/<int:id>/', views.savings_transaction_history, name='savings_transaction_history'),
    # path('savings-deposit-search/', views.savings_deposit_search, name='savings_deposit_search'),
    # path('savings-withdraw-search/', views.savings_withdraw_search, name='savings_withdraw_search'),





    path('dps-search/', views.dps_search, name='dps_search'),
    path('dps-list/', views.dps_list, name='dps_list'),
    path('dps-create/<str:account_number>/', views.dps_create, name='dps_create'),
    path('dps-schedule/<int:id>/', views.dps_schedule, name='dps_schedule'),
    path('dps-deposit/<int:id>/', views.dps_deposit, name='dps_deposit'),
    path('dps-withdraw/<int:id>/', views.dps_withdraw, name='dps_withdraw'),
    path('dps-transaction/<int:id>/', views.dps_transaction, name='dps_transaction'),
    # path('dps-deposit-search/', views.dps_deposit_search, name='dps_deposit_search'),
    # path('dps-withdraw-search/', views.dps_withdraw_search, name='dps_withdraw_search'),
    path('dps-close-search/', views.dps_close_search, name='dps_close_search'),
    path('dps-close/<int:id>/', views.dps_close, name='dps_close'),



    path('share-list/', views.share_list, name='share_list'),
    path('share-create/<str:account_number>/', views.share_create, name='share_create'),
    path('share-search/', views.share_search, name='share_search'),
    path('share-deposit/<int:share_id>/', views.share_deposit, name='share_deposit'),
    # path('share-deposit-search/', views.share_deposit_search, name='share_deposit_search'),
    # path('share-withdraw-search/', views.share_withdraw_search, name='share_withdraw_search'),
    path('share-profit-withdraw-search/', views.share_profit_withdraw_search, name='share_profit_withdraw_search'),
    path('share-withdraw/<int:share_id>/', views.share_withdraw, name='share_withdraw'),
    path('share-transfer/<int:share_id>/', views.share_transfer, name='share_transfer'),
    path('share-profit-withdraw/<int:share_id>/', views.share_profit_withdraw, name='share_profit_withdraw'),
    path('share-transaction-history/<int:share_id>/', views.share_transaction_history, name='share_transaction_history'),

    # path('bank_withdraw/', views.bank_withdraw, name='bank_withdraw'),
    # path('bank_deposit/', views.bank_deposit, name='bank_deposit'),
    
    path('bank-transactions/', views.bank_transaction_view, name='bank_transaction_view'),
    path('voucher-transactions/', views.voucher_transaction_view, name='voucher_transaction_view'),
    
    path('package/', views.package, name='package'),
    path('delete-search/', views.delete_search, name='delete_search'),
    path('delete-customer/<int:id>/', views.delete_customer, name='delete_customer'),
    path('delete-dps/<int:id>/', views.dps_delete, name='dps_delete'),
    path('delete-share/<int:share_id>/', views.share_delete, name='share_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('primary_setup.urls')),
    path('', include('otrans.urls')),
    path('report/', include('report.urls')),
    path('sheet/', include('sheet.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('sms/', include('sms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sms_single/', views.sms_single, name='sms_single'),
    path('sms_bulk/', views.sms_bulk, name='sms_bulk'),
    path('sms_customer/', views.sms_customer, name='sms_customer'),
    path('sms_report/', views.sms_report, name='sms_report'),
]

app1/models.py
from django.db import models
import random
import string
from datetime import timedelta

from django.db.models.signals import post_save
from django.dispatch import receiver
from otrans.models import Passbook
from primary_setup.models import Holiday, CustomUser, DPSScheme, Bank
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class CustomerManager(BaseUserManager):
    def create_user(self, account_number, password=None, **extra_fields):

        user = self.model(account_number=account_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    
    
class Customer(AbstractBaseUser):
 
    joining_date = models.DateField()
    account_number = models.CharField(max_length=50)
    customer_photo = models.ImageField(upload_to='photos/', blank=True, null=True)
    
    customer_name = models.CharField(max_length=100, blank=True, null=True)
    customer_father = models.CharField(max_length=100, blank=True, null=True)
    customer_mother = models.CharField(max_length=100, blank=True, null=True)
    
    customer_current_address = models.TextField(blank=True, null=True)
    customer_permanent_address = models.TextField(blank=True, null=True)
    customer_nid = models.CharField(max_length=20, blank=True, null=True)
    customer_mobile = models.CharField(max_length=11, blank=True, null=True)
    
    share_count = models.PositiveIntegerField(blank=True, null=True)
    mediator_name = models.CharField(max_length=100, blank=True, null=True)
    recommender_name = models.CharField(max_length=100, blank=True, null=True)
    recommender_relation = models.CharField(max_length=100, blank=True, null=True)
    recommender_mobile = models.CharField(max_length=11, blank=True, null=True)

    customer_signature = models.ImageField(upload_to="signatures/", blank=True, null=True)
    recommender_signature = models.ImageField(upload_to="signatures/", blank=True, null=True)



    nominee_name = models.CharField(max_length=100, blank=True, null=True)
    nominee_father = models.CharField(max_length=100, blank=True, null=True)
    nominee_mother = models.CharField(max_length=100, blank=True, null=True)
    nominee_relation = models.CharField(max_length=100, blank=True, null=True)
    
    nominee_current_address = models.TextField(blank=True, null=True)
    nominee_permanent_address = models.TextField(blank=True, null=True)
    
    nominee_nid = models.CharField(max_length=20, blank=True, null=True)
    nominee_mobile = models.CharField(max_length=15, blank=True, null=True)
    
    nominee_photo = models.ImageField(upload_to="photos/", blank=True, null=True)
    nominee_signature = models.ImageField(upload_to="signatures/", blank=True, null=True)
    president_signature = models.ImageField(upload_to="signatures/", blank=True, null=True)

    USERNAME_FIELD = 'account_number'
    

   
@receiver(post_save, sender=Customer)
def create_general_ac(sender, instance, created, **kwargs):
    if created:
        GeneralAC.objects.create(customer=instance, balance=0)
        SavingsAC.objects.create(customer=instance, balance=0)
        

class GeneralAC(models.Model):
    STATUS_CHOICES = [
        ('Active', 'Active'),
        ('Close', 'Close'),
    ]
    
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total_deposit = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_withdraw = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    balance = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Active')

    def __str__(self):
        return f"{self.customer.customer_name} - {self.status}"

class GeneralTransactionHistory(models.Model):
    TRANSACTION_TYPE_CHOICES = [
        ('deposit', 'Deposit'),
        ('withdraw', 'Withdraw'),
    ]
    ASSET_TYPE_CHOICES = [
        ('debit', 'debit'),
        ('credit', 'credit'),
    ]
    asset_type = models.CharField(max_length=10, choices=ASSET_TYPE_CHOICES, blank=True, null=True)

    account = models.ForeignKey(GeneralAC, on_delete=models.CASCADE, related_name='general_transaction_history')
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES)
    date = models.DateTimeField(null=True, blank=True)

    amount = models.DecimalField(max_digits=10, decimal_places=2)
    note = models.CharField(max_length=200, null=True, blank=True)
    month_note = models.CharField(max_length=200, null=True, blank=True)
    purpose_note = models.CharField(max_length=200, null=True, blank=True)
    VoucherID = models.CharField(max_length=50, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.VoucherID:
            self.VoucherID = ''.join(random.choices(string.ascii_lowercase + string.digits, k=15))
        self.asset_type = self.asset_type or ('debit' if self.transaction_type == 'deposit' else 'credit')
        super().save(*args, **kwargs)


class SavingsAC(models.Model):
    STATUS_CHOICES = [
        ('Active', 'Active'),
        ('Close', 'Close'),
    ]
    
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total_deposit = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_withdraw = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    balance = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Active')

    def __str__(self):
        return f"{self.customer.customer_name} - {self.status}"

class SavingsTransactionHistory(models.Model):
    TRANSACTION_TYPE_CHOICES = [
        ('deposit', 'Deposit'),
        ('withdraw', 'Withdraw'),
    ]

    ASSET_TYPE_CHOICES = [
        ('debit', 'debit'),
        ('credit', 'credit'),
    ]
    asset_type = models.CharField(max_length=10, choices=ASSET_TYPE_CHOICES, blank=True, null=True)
    
    account = models.ForeignKey(SavingsAC, on_delete=models.CASCADE, related_name='savings_transaction_history')
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE_CHOICES)
    date = models.DateTimeField(null=True, blank=True)

    amount = models.DecimalField(max_digits=10, decimal_places=2)
    note = models.CharField(max_length=200, null=True, blank=True)
    VoucherID = models.CharField(max_length=50, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.VoucherID:
            self.VoucherID = ''.join(random.choices(string.ascii_lowercase + string.digits, k=15))
        self.asset_type = self.asset_type or ('debit' if self.transaction_type == 'deposit' else 'credit')
        super().save(*args, **kwargs)




class DPS(models.Model):

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('closed', 'Closed'),
    ]
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)

    created_date = models.DateField()
    dps_scheme = models.ForeignKey(DPSScheme, on_delete=models.CASCADE, default=1)

    amount_per_installments = models.DecimalField(max_digits=10, decimal_places=2)
    number_of_installments = models.IntegerField()

    profit_percent = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    profit_taka = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    fine_per_missed_installment = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    dps_opening_charge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    dps_closing_charge = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    bonus = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    start_installment = models.IntegerField(default=0)
    leger_no = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    installment_sequence = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_id = models.CharField(max_length=15, unique=True, editable=False)

    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    
    total_deposit = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    total_withdraw = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    processed_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)

    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='active')

    @property
    def paid_installments(self):
        return self.dps_installment_schedules.filter(installment_status='paid').count()
    
    @property
    def due(self):
        return self.total_amount - self.balance

    def save(self, *args, **kwargs):
        if not self.transaction_id:
            self.transaction_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=15))
        if not self.start_date:
            self.start_date = self.created_date + timedelta(days=self.start_installment)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"DPS : {self.transaction_id}"


    def generate_installment_schedule(self):
        schedule = []
        
        start_date = self.created_date + timedelta(days=self.start_installment)
        current_date = start_date
        holidays = Holiday.objects.values_list('date', flat=True)

        # Determine the interval based on the DPS scheme's payment sequence
        if self.dps_scheme.payment_sequence:
            interval_days = self.dps_scheme.payment_sequence
        else:
            interval_days = 1  # Default to daily if no payment_sequence is provided

        for i in range(self.number_of_installments):
            skipped_date = None

templates/app1/dps/dps_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add DPS{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_details.css' %}">
<link rel="stylesheet" href="{% static 'app1/dps.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Retrieve and parse the JSON data from the Django template
        const dpsSchemes = JSON.parse(document.getElementById('dps-schemes-data').textContent);

        const schemeSelect = document.getElementById('id_dps_scheme');
        const installmentSequenceInput = document.getElementById('id_installment_sequence');

        // Function to update installment sequence based on selected scheme
        function updateInstallmentSequence() {
            const selectedSchemeId = parseInt(schemeSelect.value);
            const selectedScheme = dpsSchemes.find(scheme => scheme.id === selectedSchemeId);

            if (selectedScheme) {
                installmentSequenceInput.value = selectedScheme.payment_sequence;
            }
        }

        // Event listener for scheme change
        schemeSelect.addEventListener('change', updateInstallmentSequence);

        // Update installment sequence on page load based on the initially selected scheme
        updateInstallmentSequence();
    });
</script>

{% endblock %}

{% block content %}
<h2>Add DPS</h2>
<div class="div1">
    <table>
        <tr>
            <th>Account No.</th>
            <td>{{ customer.account_number }}</td>
        </tr>
        <tr>
            <th>Customer Name</th>
            <td>{{ customer.customer_name }}</td>
        </tr>
        <tr>
            <th>Father</th>
            <td>{{ customer.customer_father }}</td>
        </tr>
        <tr>
            <th>Mother</th>
            <td>{{ customer.customer_mother }}</td>
        </tr>
        <tr>
            <th>Mobile Number</th>
            <td>{{ customer.customer_mobile }}</td>
        </tr>
        <tr>
            <th>Current Address</th>
            <td>{{ customer.customer_current_address }}</td>
        </tr>
        <tr>
            <th>Permanent Address</th>
            <td>{{ customer.customer_permanent_address }}</td>
        </tr>
    </table>
    
    <div class="img-container">
        {% if customer.customer_photo %}
        <div>
            <img src="{{ customer.customer_photo.url }}" class="centered-image">
        </div>
        {% endif %}
    </div>
</div>
<div class="div2">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
<div>
    {{ dps_schemes|json_script:"dps-schemes-data" }}
</div>
{% endblock %}

{% block scripts %}
<script>
    function calculateValues() {
        const amount_per_installments = parseFloat(document.getElementById('id_amount_per_installments').value) || 0;
        const number_of_installments = parseFloat(document.getElementById('id_number_of_installments').value) || 0;
        const profitPercent = parseFloat(document.getElementById('id_profit_percent').value) || 0;
        const schemeId = document.getElementById('id_dps_scheme').value;

        // Calculate Profit Taka
        const totalAmountWithoutProfit = amount_per_installments * number_of_installments;
        const profitTaka = totalAmountWithoutProfit * (profitPercent / 100);
        document.getElementById('id_profit_taka').value = profitTaka.toFixed(2);

        // Calculate Total Amount
        const totalAmount = totalAmountWithoutProfit + profitTaka;
        document.getElementById('id_total_amount').value = totalAmount.toFixed(2);

        // Set Installment Sequence based on selected scheme
        let installmentSequence = '';
        if (schemeId) {
            const scheme = dpsSchemes.find(s => s.id === parseInt(schemeId));
            if (scheme) {
                installmentSequence = scheme.payment_sequence;
            }
        }
        document.getElementById('id_installment_sequence').value = installmentSequence;
    }

    document.getElementById('id_amount_per_installments').addEventListener('input', calculateValues);
    document.getElementById('id_number_of_installments').addEventListener('input', calculateValues);
    document.getElementById('id_profit_percent').addEventListener('input', calculateValues);
    
</script>

<script>
    $(function() {
        var today = new Date();
        var formattedDate = $.datepicker.formatDate('yy-mm-dd', today);

        $("#id_created_date").datepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: today,
        }).val(formattedDate);
    });
</script>
{% endblock %}

templates/app1/dps/dps_dw.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DPS AC {{transaction_type}}{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/general.css' %}">
{% endblock %}

{% block content %}

    <h1>DPS AC {{transaction_type}}</h1>

    <div class="table-container1" style="display: flex; gap: 25px; margin: 20px 0;">

        <table>
            <tr>
                <td>DPS Scheme</td>
                <td>{{ dps.dps_scheme }}</td>
            </tr>
            <tr>
                <td>Account No</td>
                <td>{{ dps.customer.account_number }}</td>
            </tr>
            <tr>
                <td>Customer Name</td>
                <td>{{ dps.customer.customer_name }}</td>
            </tr>
            <tr>
                <td>Start Date</td>
                <td>{{ dps.start_date }}</td>
            </tr>
            <tr>
                <td>End Date</td>
                <td>{{ dps.end_date }}</td>
            </tr>
            <tr>
                <td>Profit</td>
                <td>{{ dps.profit_percent }}%</td>
            </tr>
        </table>
        <table>
            <tr>
                <td>Installments</td>
                <td>{{dps.paid_installments}}/{{ dps.number_of_installments }}</td>
            </tr>
            <tr>
                <td>Installment Amount</td>
                <td>{{ dps.amount_per_installments }}</td>
            </tr>
            <tr>
                <td>Total Amount</td>
                <td>{{ dps.total_amount }}</td>
            </tr>
            <tr>
                <td>Balance</td>
                <td>{{ dps.balance }}</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>{{ dps.get_status_display }}</td>
            </tr>
            <tr>
                <td>-</td>
                <td>-</td>
            </tr>
        </table>
    </div>
    

    <div class="div2">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>


{% endblock %}

templates/app1/dps/dps_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DPS List{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/customer_list.css' %}">
<style>
    .main{
        width: 85%;
    }
    th{
        background-color: var(--primary-color);
        color: white;
        
    }
    td{
        text-align: center;
    }
    table.dataTable > thead > tr > th, table.dataTable > thead > tr > td {
        text-align: center;
    }
    .trans-btn {
        color: white;
        text-decoration: none;
        padding: 3px 10px;
        margin: 3px;
        display: inline-block;
        border-radius: 25px;
    }
    .deposit-btn {
        background: green;
    }
    .withdraw-btn {
        background: red;
    }
    .trans-his-btn {
        background: black;
    }
    .schedule-btn {
        background: var(--primary-color);
    }
</style>
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.3/css/dataTables.dataTables.css">
{% endblock %}

{% block content %}

    <h2>DPS AC List</h2>
    
    {% if data %}
    <div class="table-container">
        <table id="myTable" class="display" style="width:100%">
            <thead>
                <tr>
                 
                    <th>Account No</th>
                    <th>Action</th>
                    <th>DPS Scheme</th>
     
                    <th>Customer Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>profit</th>
                    <th>Installments</th>
                    <th>Installments Amount</th>
                    <th>Total Amount</th>
                    <th>Balance</th>
                    <th>Due</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for info in data %}
                    <tr>
                        <td>{{ info.customer.account_number }}</td>
                        <td>
                            <a href="{% url 'dps_schedule' id=info.id %}" class="trans-btn schedule-btn">Schedule</i></a> <br>
                            <a href="{% url 'dps_deposit' id=info.id %}" class="trans-btn deposit-btn">Deposit</a> <br>
                            <a href="{% url 'dps_withdraw' id=info.id %}" class="trans-btn withdraw-btn">Withdraw</a> <br>
                            <a href="{% url 'dps_transaction' id=info.id %}" class="trans-btn trans-his-btn">Transactions</a> <br>
                        </td>
                        <td>{{ info.dps_scheme }}</td>
         
                      
                        <td>{{ info.customer.customer_name }}</td>
                        <td>{{ info.start_date }}</td>
                        <td>{{ info.end_date }}</td>
                        <td>{{ info.profit_percent }}%</td>
                        <td>{{ info.paid_installments }}/{{ info.number_of_installments }}</td>
                        <td>{{ info.amount_per_installments }}</td>
                        <td>{{ info.total_amount }}</td>
                        <td>{{ info.balance }}</td>
                        <td>{{ info.due_amount }}</td>
                        <td>{{ info.get_status_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    {% else %}
        <p>No Loan found for the active branch.</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/2.1.3/js/dataTables.js"></script>
    <script>
        $(document).ready(function() {
            $('#myTable').DataTable();
        });
    </script>
{% endblock %}

templates/app1/dps/dps_transaction.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DPS Transactions{% endblock %}
{% block style_links %}
<link rel="stylesheet" href="{% static 'app1/general.css' %}">
{% endblock %}
{% block content %}

<h2>DPS AC Transaction History</h2>



<div class="table-container1" style="display: flex; gap: 25px; margin: 20px 0;">

  <table>
      <tr>
          <td>DPS Scheme</td>
          <td>{{ dps.dps_scheme }}</td>
      </tr>
      <tr>
          <td>Account No</td>
          <td>{{ dps.customer.account_number }}</td>
      </tr>
      <tr>
          <td>Customer Name</td>
          <td>{{ dps.customer.customer_name }}</td>
      </tr>
      <tr>
          <td>Start Date</td>
          <td>{{ dps.start_date }}</td>
      </tr>
      <tr>
          <td>End Date</td>
          <td>{{ dps.end_date }}</td>
      </tr>
      <tr>
          <td>Profit</td>
          <td>{{ dps.profit_percent }}%</td>
      </tr>
  </table>
  <table>
      <tr>
          <td>Installments</td>
          <td>{{dps.paid_installments}}/{{ dps.number_of_installments }}</td>
      </tr>
      <tr>
          <td>Installment Amount</td>
          <td>{{ dps.amount_per_installments }}</td>
      </tr>
      <tr>
          <td>Total Amount</td>
          <td>{{ dps.total_amount }}</td>
      </tr>
      <tr>
          <td>Balance</td>
          <td>{{ dps.balance }}</td>
      </tr>
      <tr>
          <td>Status</td>
          <td>{{ dps.get_status_display }}</td>
      </tr>
      <tr>
          <td>-</td>
          <td>-</td>
      </tr>
  </table>
</div>


<table>
  <thead>
    <tr>
      <th>TrxID</th>
      <th>Date</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Note</th>
    </tr>
  </thead>
  <tbody>

    {% for transaction in transactions %}
    <tr>
      <td>{{ transaction.VoucherID }}</td>
      <td>{{ transaction.date|date:"Y-m-d" }}</td>
      <td>{{ transaction.get_transaction_type_display }}</td>
      <td>
        {% if transaction.transaction_type == 'deposit' %}<i class="fa-solid fa-plus" style="color: green"></i>
        {% else %}<i class="fa-solid fa-minus" style="color: red"></i>
        {% endif %}
        {{ transaction.amount }}
      </td>
      <td>{{ transaction.note|default:"" }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock %}